import type { Banner, Category, Customer, Order, Product, Review } from "@/types/store";

export const categories: Category[] = [
  {
    id: "cat-1",
    name: "Women",
    slug: "women",
    description: "Modern essentials for everyday elegance.",
    image: "https://images.unsplash.com/photo-1529139574466-a303027c1d8b?auto=format&fit=crop&w=1000&q=80",
    featured: true,
  },
  {
    id: "cat-2",
    name: "Men",
    slug: "men",
    description: "Sharp staples and easy layering pieces.",
    image: "https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=1000&q=80",
    featured: true,
  },
  {
    id: "cat-3",
    name: "Accessories",
    slug: "accessories",
    description: "Premium add-ons with everyday utility.",
    image: "https://images.unsplash.com/photo-1523170335258-f5ed11844a49?auto=format&fit=crop&w=1000&q=80",
    featured: true,
  },
  {
    id: "cat-4",
    name: "Home Living",
    slug: "home-living",
    description: "Calm, elevated details for your living spaces.",
    image: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=1000&q=80",
    featured: false,
  },
];

export const products: Product[] = [
  {
    id: "prod-1",
    slug: "aurora-silk-shirt",
    name: "Aurora Silk Shirt",
    sku: "AUR-001",
    shortDescription: "Lightweight everyday silk with a tailored drape.",
    description:
      "Crafted from a soft premium silk blend, the Aurora shirt brings structure and polish to workdays and dinners alike. Designed for effortless styling across seasons.",
    price: 3499,
    compareAtPrice: 4999,
    discount: 30,
    costPrice: 2200,
    stock: 24,
    lowStockThreshold: 8,
    category: "Women",
    subcategory: "Shirts",
    brand: "Aster & Co.",
    images: [
      "https://images.unsplash.com/photo-1529139574466-a303027c1d8b?auto=format&fit=crop&w=900&q=80",
      "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=900&q=80",
      "https://images.unsplash.com/photo-1483985988355-763728e1935b?auto=format&fit=crop&w=900&q=80",
    ],
    thumbnail: "https://images.unsplash.com/photo-1529139574466-a303027c1d8b?auto=format&fit=crop&w=800&q=80",
    tags: ["silk", "new", "premium"],
    rating: 4.8,
    reviewCount: 210,
    featured: true,
    bestSeller: true,
    newArrival: true,
    isPublished: true,
    variants: [
      { id: "v-1", name: "S", sku: "AUR-001-S", price: 3499, stock: 7, attributes: { Size: "S", Color: "Ivory" } },
      { id: "v-2", name: "M", sku: "AUR-001-M", price: 3499, stock: 9, attributes: { Size: "M", Color: "Ivory" } },
      { id: "v-3", name: "L", sku: "AUR-001-L", price: 3499, stock: 8, attributes: { Size: "L", Color: "Ivory" } },
    ],
    seoTitle: "Aurora Silk Shirt | Premium Womenswear",
    seoDescription: "Premium silk shirt with elegant tailored fit for women.",
  },
  {
    id: "prod-2",
    slug: "forge-canvas-jacket",
    name: "Forge Canvas Jacket",
    sku: "FOR-012",
    shortDescription: "Layer-ready utility jacket for everyday movement.",
    description:
      "An understated utility jacket with a rugged finish, versatile pockets, and a breathable structure that moves with you from commute to weekend outings.",
    price: 4999,
    compareAtPrice: 6299,
    discount: 20,
    costPrice: 3100,
    stock: 16,
    lowStockThreshold: 6,
    category: "Men",
    subcategory: "Outerwear",
    brand: "North Avenue",
    images: [
      "https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=900&q=80",
      "https://images.unsplash.com/photo-1507679799987-c73779587ccf?auto=format&fit=crop&w=900&q=80",
      "https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=900&q=80",
    ],
    thumbnail: "https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=800&q=80",
    tags: ["utility", "new"],
    rating: 4.7,
    reviewCount: 154,
    featured: true,
    bestSeller: false,
    newArrival: true,
    isPublished: true,
    variants: [
      { id: "v-4", name: "M", sku: "FOR-012-M", price: 4999, stock: 6, attributes: { Size: "M", Color: "Charcoal" } },
      { id: "v-5", name: "L", sku: "FOR-012-L", price: 4999, stock: 5, attributes: { Size: "L", Color: "Charcoal" } },
      { id: "v-6", name: "XL", sku: "FOR-012-XL", price: 4999, stock: 5, attributes: { Size: "XL", Color: "Charcoal" } },
    ],
    seoTitle: "Forge Canvas Jacket | Men’s Outerwear",
    seoDescription: "Layer-ready canvas jacket with premium utility detailing.",
  },
  {
    id: "prod-3",
    slug: "soho-rose-watch",
    name: "Soho Rose Watch",
    sku: "SOH-460",
    shortDescription: "Minimal luxury watch with brushed rose detailing.",
    description:
      "A clean Swiss-inspired watch face, comfortable strap, and refined finishing touches designed to stand out without overwhelming your look.",
    price: 7999,
    compareAtPrice: 9999,
    discount: 20,
    costPrice: 5100,
    stock: 11,
    lowStockThreshold: 3,
    category: "Accessories",
    subcategory: "Watches",
    brand: "Lune Studio",
    images: [
      "https://images.unsplash.com/photo-1523170335258-f5ed11844a49?auto=format&fit=crop&w=900&q=80",
      "https://images.unsplash.com/photo-1542496658-e33a6d0d50f6?auto=format&fit=crop&w=900&q=80",
      "https://images.unsplash.com/photo-1490367532201-b9bc1dc483f6?auto=format&fit=crop&w=900&q=80",
    ],
    thumbnail: "https://images.unsplash.com/photo-1523170335258-f5ed11844a49?auto=format&fit=crop&w=800&q=80",
    tags: ["luxury", "bestseller"],
    rating: 4.9,
    reviewCount: 332,
    featured: true,
    bestSeller: true,
    newArrival: false,
    isPublished: true,
    variants: [
      { id: "v-7", name: "Classic", sku: "SOH-460-C", price: 7999, stock: 6, attributes: { Strap: "Rose Gold", Size: "42mm" } },
      { id: "v-8", name: "Leather", sku: "SOH-460-L", price: 8499, stock: 5, attributes: { Strap: "Leather", Size: "42mm" } },
    ],
    seoTitle: "Soho Rose Watch | Premium Accessories",
    seoDescription: "Luxury rose-toned watch for refined everyday wear.",
  },
  {
    id: "prod-4",
    slug: "mila-ceramic-vase",
    name: "Mila Ceramic Vase",
    sku: "MIL-540",
    shortDescription: "Statement vase with sculptural form and soft neutral glaze.",
    description:
      "A modern artisan vase finished in a subtle matte glaze, designed to elevate shelves, side tables, and gallery walls with its soft organic silhouette.",
    price: 2499,
    compareAtPrice: 3399,
    discount: 26,
    costPrice: 1500,
    stock: 18,
    lowStockThreshold: 6,
    category: "Home Living",
    subcategory: "Decor",
    brand: "Atelier Form",
    images: [
      "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=900&q=80",
      "https://images.unsplash.com/photo-1517705008128-361805f42e86?auto=format&fit=crop&w=900&q=80",
      "https://images.unsplash.com/photo-1494526585095-c41746248156?auto=format&fit=crop&w=900&q=80",
    ],
    thumbnail: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=800&q=80",
    tags: ["home", "decor"],
    rating: 4.6,
    reviewCount: 90,
    featured: false,
    bestSeller: false,
    newArrival: true,
    isPublished: true,
    variants: [
      { id: "v-9", name: "Tall", sku: "MIL-540-T", price: 2499, stock: 10, attributes: { Size: "Tall", Finish: "Sand" } },
      { id: "v-10", name: "Short", sku: "MIL-540-S", price: 2299, stock: 8, attributes: { Size: "Short", Finish: "Sand" } },
    ],
    seoTitle: "Mila Ceramic Vase | Modern Home Decor",
    seoDescription: "Sculptural ceramic vase with neutral matte finish for elevated interiors.",
  },
  {
    id: "prod-5",
    slug: "nova-trainer",
    name: "Nova Trainer",
    sku: "NOVA-223",
    shortDescription: "Responsive daily trainer built for city movement.",
    description:
      "Engineered with cushioned support and a breathable upper, the Nova Trainer delivers a fast footfall feel for busy days and balanced movement.",
    price: 4199,
    compareAtPrice: 5699,
    discount: 26,
    costPrice: 2600,
    stock: 21,
    lowStockThreshold: 7,
    category: "Men",
    subcategory: "Footwear",
    brand: "Summit Run",
    images: [
      "https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=900&q=80",
      "https://images.unsplash.com/photo-1600185365483-26d7a4cc7519?auto=format&fit=crop&w=900&q=80",
      "https://images.unsplash.com/photo-1543508282-6319a3e2621f?auto=format&fit=crop&w=900&q=80",
    ],
    thumbnail: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=800&q=80",
    tags: ["sport", "popular"],
    rating: 4.5,
    reviewCount: 127,
    featured: true,
    bestSeller: true,
    newArrival: false,
    isPublished: true,
    variants: [
      { id: "v-11", name: "7", sku: "NOVA-223-7", price: 4199, stock: 5, attributes: { Size: "7", Color: "White" } },
      { id: "v-12", name: "8", sku: "NOVA-223-8", price: 4199, stock: 7, attributes: { Size: "8", Color: "White" } },
      { id: "v-13", name: "9", sku: "NOVA-223-9", price: 4199, stock: 9, attributes: { Size: "9", Color: "White" } },
    ],
    seoTitle: "Nova Trainer | Premium Footwear",
    seoDescription: "Responsive everyday trainer with city-ready comfort.",
  },
  {
    id: "prod-6",
    slug: "solstice-hoodie",
    name: "Solstice Hoodie",
    sku: "SOL-880",
    shortDescription: "Ultra-soft fleece for elevated off-duty comfort.",
    description:
      "Laid-back warmth meets refined detailing in a heavyweight fleece hoodie designed for all-day comfort and effortless layering.",
    price: 2899,
    compareAtPrice: 3899,
    discount: 25,
    costPrice: 1700,
    stock: 32,
    lowStockThreshold: 10,
    category: "Women",
    subcategory: "Sweats",
    brand: "Pine & Thread",
    images: [
      "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=900&q=80",
      "https://images.unsplash.com/photo-1483985988355-763728e1935b?auto=format&fit=crop&w=900&q=80",
      "https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=900&q=80",
    ],
    thumbnail: "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=800&q=80",
    tags: ["comfort", "soft"],
    rating: 4.7,
    reviewCount: 163,
    featured: false,
    bestSeller: true,
    newArrival: true,
    isPublished: true,
    variants: [
      { id: "v-14", name: "S", sku: "SOL-880-S", price: 2899, stock: 16, attributes: { Size: "S", Color: "Stone" } },
      { id: "v-15", name: "M", sku: "SOL-880-M", price: 2899, stock: 12, attributes: { Size: "M", Color: "Stone" } },
      { id: "v-16", name: "L", sku: "SOL-880-L", price: 2899, stock: 4, attributes: { Size: "L", Color: "Stone" } },
    ],
    seoTitle: "Solstice Hoodie | Premium Casualwear",
    seoDescription: "Soft fleece hoodie with refined, comfortable layering design.",
  },
];

export const reviews: Review[] = [
  {
    id: "r-1",
    customer: "Aisha K.",
    rating: 5,
    title: "Beautiful finish and effortless fit",
    comment: "The fabric feels premium and the tailoring is excellent. I wear it for both work and dinners.",
    date: "2026-05-11",
    verified: true,
  },
  {
    id: "r-2",
    customer: "Rohit S.",
    rating: 4,
    title: "Perfect daily layering piece",
    comment: "Great quality and the color is exactly as pictured. The fit is comfortable and modern.",
    date: "2026-06-18",
    verified: true,
  },
  {
    id: "r-3",
    customer: "Meera P.",
    rating: 5,
    title: "Quick delivery and great quality",
    comment: "Loved the packaging and the product arrived in pristine condition. It looks premium in person.",
    date: "2026-07-02",
    verified: true,
  },
];

export const topBanners: Banner[] = [
  {
    id: "b-1",
    title: "Curated essentials for modern Indian living",
    subtitle: "Fresh arrivals, elevated staples, and lifestyle upgrades for every day.",
    cta: "Shop now",
    href: "/shop",
    desktopImage: "https://images.unsplash.com/photo-1524758631624-e2822e304c36?auto=format&fit=crop&w=1600&q=80",
    mobileImage: "https://images.unsplash.com/photo-1524758631624-e2822e304c36?auto=format&fit=crop&w=900&q=80",
    position: "hero",
  },
  {
    id: "b-2",
    title: "Up to 40% off premium picks",
    subtitle: "End-of-season savings on curated menswear and home essentials.",
    cta: "Explore deals",
    href: "/shop?filter=sale",
    desktopImage: "https://images.unsplash.com/photo-1483985988355-763728e1935b?auto=format&fit=crop&w=1600&q=80",
    mobileImage: "https://images.unsplash.com/photo-1483985988355-763728e1935b?auto=format&fit=crop&w=900&q=80",
    position: "promo",
  },
];

export const recentOrders: Order[] = [
  { id: "#10012", customer: "Vikram R.", total: 3299, status: "Shipped", date: "2026-08-12", paymentStatus: "Paid" },
  { id: "#10009", customer: "Nisha M.", total: 4999, status: "Confirmed", date: "2026-08-10", paymentStatus: "Paid" },
  { id: "#10005", customer: "Aditya K.", total: 2499, status: "Delivered", date: "2026-08-08", paymentStatus: "Paid" },
  { id: "#10002", customer: "Pooja S.", total: 7999, status: "Processing", date: "2026-08-05", paymentStatus: "Pending" },
];

export const customerData: Customer[] = [
  { id: "c-1", name: "Aisha K.", email: "aisha@example.com", totalSpent: 18999, orders: 4, active: true },
  { id: "c-2", name: "Rohit S.", email: "rohit@example.com", totalSpent: 12999, orders: 2, active: true },
  { id: "c-3", name: "Meera P.", email: "meera@example.com", totalSpent: 8699, orders: 1, active: false },
  { id: "c-4", name: "Harsh J.", email: "harsh@example.com", totalSpent: 24999, orders: 5, active: true },
];
